export const initialState = [
  {
    id: 1,
    name: "ДомСельхозРаботы",
    address: "г. Санкт-Петербург, ул. Карусельная, д. 14, оф. 525",
    employees: [
      {
        id: 1,
        firstName: "Иван",
        lastName: "Петров",
        position: "Старший монтажник",
      },
      {
        id: 2,
        firstName: "Александр",
        lastName: "Сидоров",
        position: "Инженер-строитель",
      },
      {
        id: 3,
        firstName: "Екатерина",
        lastName: "Иванова",
        position: "Архитектор",
      },
      {
        id: 4,
        firstName: "Сергей",
        lastName: "Кузнецов",
        position: "Прораб",
      },
      {
        id: 5,
        firstName: "Анна",
        lastName: "Смирнова",
        position: "Монтажник",
      },
      {
        id: 6,
        firstName: "Дмитрий",
        lastName: "Федоров",
        position: "Строитель",
      },
      {
        id: 7,
        firstName: "Ольга",
        lastName: "Морозова",
        position: "Директор",
      },
      {
        id: 8,
        firstName: "Павел",
        lastName: "Николаев",
        position: "Инженер",
      },
      {
        id: 9,
        firstName: "Мария",
        lastName: "Егорова",
        position: "Архитектор",
      },
      {
        id: 10,
        firstName: "Никита",
        lastName: "Козлов",
        position: "Строитель",
      },
    ],
  },
  {
    id: 2,
    name: "СтройМастер",
    address: "г. Москва, ул. Ленина, д. 10, оф. 201",
    employees: [
      {
        id: 1,
        firstName: "Олег",
        lastName: "Игнатьев",
        position: "Прораб",
      },
      {
        id: 2,
        firstName: "Татьяна",
        lastName: "Волкова",
        position: "Инженер-строитель",
      },
      {
        id: 3,
        firstName: "Артем",
        lastName: "Комаров",
        position: "Строитель",
      },
      {
        id: 4,
        firstName: "Светлана",
        lastName: "Павлова",
        position: "Архитектор",
      },
      {
        id: 5,
        firstName: "Игорь",
        lastName: "Медведев",
        position: "Монтажник",
      },
      {
        id: 6,
        firstName: "Елена",
        lastName: "Соколова",
        position: "Строитель",
      },
      {
        id: 7,
        firstName: "Андрей",
        lastName: "Тихонов",
        position: "Директор",
      },
      {
        id: 8,
        firstName: "Юлия",
        lastName: "Андреева",
        position: "Инженер",
      },
      {
        id: 9,
        firstName: "Владимир",
        lastName: "Сергеев",
        position: "Строитель",
      },
      {
        id: 10,
        firstName: "Марина",
        lastName: "Новикова",
        position: "Архитектор",
      },
    ],
  },
  {
    id: 3,
    name: "ГК АдептСтрой",
    address: "г. Нижний Новгород, пр. Гагарина, д. 20, помещ. 189",
    employees: [
      {
        id: 1,
        firstName: "Илья",
        lastName: "Ростов",
        position: "Прораб",
      },
      {
        id: 2,
        firstName: "Наталья",
        lastName: "Ростова",
        position: "Инженер-строитель",
      },
      {
        id: 3,
        firstName: "Вера",
        lastName: "Ростова",
        position: "Строитель",
      },
      {
        id: 4,
        firstName: "Николай",
        lastName: "Ростов",
        position: "Архитектор",
      },
      {
        id: 5,
        firstName: "Наталья",
        lastName: "Ростова",
        position: "Монтажник",
      },
      {
        id: 6,
        firstName: "Петр",
        lastName: "Ростов",
        position: "Строитель",
      },
      {
        id: 7,
        firstName: "Николай",
        lastName: "Болконский",
        position: "Директор",
      },
      {
        id: 8,
        firstName: "Андрей",
        lastName: "Болконский",
        position: "Инженер",
      },
      {
        id: 9,
        firstName: "Марья",
        lastName: "Болконская",
        position: "Строитель",
      },
      {
        id: 10,
        firstName: "Елизавета",
        lastName: "Болконская",
        position: "Архитектор",
      },
    ],
  },
  {
    id: 4,
    name: "РосРемонт",
    address: "г. Иркутск, ул. Декабрьских Событий, д. 88",
    employees: [
      {
        id: 1,
        firstName: "Василий",
        lastName: "Курагин",
        position: "Прораб",
      },
      {
        id: 2,
        firstName: "Ипполит",
        lastName: "Курагин",
        position: "Инженер-строитель",
      },
      {
        id: 3,
        firstName: "Елена",
        lastName: "Курагина",
        position: "Строитель",
      },
      {
        id: 4,
        firstName: "Петр",
        lastName: "Безухов",
        position: "Архитектор",
      },
      {
        id: 5,
        firstName: "Анна",
        lastName: "Друбецкая",
        position: "Монтажник",
      },
      {
        id: 6,
        firstName: "Борис",
        lastName: "Друбецкой",
        position: "Строитель",
      },
      {
        id: 7,
        firstName: "Катерина",
        lastName: "Мамонтова",
        position: "Директор",
      },
      {
        id: 8,
        firstName: "Ольга",
        lastName: "Мамонтова",
        position: "Инженер",
      },
      {
        id: 9,
        firstName: "Софья",
        lastName: "Мамонтова",
        position: "Строитель",
      },
      {
        id: 10,
        firstName: "Марья",
        lastName: "Карагина",
        position: "Архитектор",
      },
    ],
  },
  {
    id: 5,
    name: "СибирьЭнерго",
    address: "г. Тюмень, ул. Киевская, д. 74А, помещ. 14",
    employees: [
      {
        id: 1,
        firstName: "Жюли",
        lastName: "Карагина",
        position: "Прораб",
      },
      {
        id: 2,
        firstName: "Марья",
        lastName: "Долохова",
        position: "Инженер-строитель",
      },
      {
        id: 3,
        firstName: "Федор",
        lastName: "Долохов",
        position: "Строитель",
      },
      {
        id: 4,
        firstName: "Марья",
        lastName: "Ахросимова",
        position: "Архитектор",
      },
      {
        id: 5,
        firstName: "Альфонс",
        lastName: "Берг",
        position: "Монтажник",
      },
      {
        id: 6,
        firstName: "Амалия",
        lastName: "Бурьенн",
        position: "Строитель",
      },
      {
        id: 7,
        firstName: "Василий",
        lastName: "Денисов",
        position: "Директор",
      },
      {
        id: 8,
        firstName: "Платон",
        lastName: "Каратаев",
        position: "Инженер",
      },
      {
        id: 9,
        firstName: "Анна",
        lastName: "Шерер",
        position: "Строитель",
      },
      {
        id: 10,
        firstName: "Петр",
        lastName: "Шиншин",
        position: "Архитектор",
      },
    ],
  },
  {
    id: 6,
    name: "Агропромэнерго",
    address: "Вологодская обл., Череповецкий р-н, д. Ясная Поляна",
    employees: [
      {
        id: 1,
        firstName: "Наполеон",
        lastName: "Бонапарт",
        position: "Прораб",
      },
      {
        id: 2,
        firstName: "Михаил",
        lastName: "Кутузов",
        position: "Инженер-строитель",
      },
      {
        id: 3,
        firstName: "Петр",
        lastName: "Багратион",
        position: "Строитель",
      },
      {
        id: 4,
        firstName: "Михаил",
        lastName: "Барклай де Толли",
        position: "Архитектор",
      },
      {
        id: 5,
        firstName: "Карл",
        lastName: "Мак",
        position: "Монтажник",
      },
      {
        id: 6,
        firstName: "Александр",
        lastName: "Мишо",
        position: "Строитель",
      },
      {
        id: 7,
        firstName: "Карл",
        lastName: "Пфуль",
        position: "Директор",
      },
      {
        id: 8,
        firstName: "Карл",
        lastName: "Толь",
        position: "Инженер",
      },
      {
        id: 9,
        firstName: "Густав",
        lastName: "Армфельт",
        position: "Строитель",
      },
      {
        id: 10,
        firstName: "Карл",
        lastName: "Багговут",
        position: "Архитектор",
      },
    ],
  },
  {
    id: 7,
    name: "АТОМЭНЕРГОМОНТАЖ",
    address: "г. Калининград, ул. 2-я Большая Окружная, д. 90",
    employees: [
      {
        id: 1,
        firstName: "Александр",
        lastName: "Балашов",
        position: "Прораб",
      },
      {
        id: 2,
        firstName: "Леонтий",
        lastName: "Беннигсен",
        position: "Инженер-строитель",
      },
      {
        id: 3,
        firstName: "Федор",
        lastName: "Буксгевден",
        position: "Строитель",
      },
      {
        id: 4,
        firstName: "Франц",
        lastName: "фон Вейпотер",
        position: "Архитектор",
      },
      {
        id: 5,
        firstName: "Людвиг",
        lastName: "фон Вольцоген",
        position: "Монтажник",
      },
      {
        id: 6,
        firstName: "Иван",
        lastName: "Греков",
        position: "Строитель",
      },
      {
        id: 7,
        firstName: "Петр",
        lastName: "Долгоруков",
        position: "Директор",
      },
      {
        id: 8,
        firstName: "Дмитрий",
        lastName: "Дохтуров",
        position: "Инженер",
      },
      {
        id: 9,
        firstName: "Алексей",
        lastName: "Ермолов",
        position: "Строитель",
      },
      {
        id: 10,
        firstName: "Петр",
        lastName: "Коновницын",
        position: "Архитектор",
      },
    ],
  },
  {
    id: 8,
    name: "СИНТЕЗ-ЭЛ",
    address: "г. Людиново, ул. К.Маркса, д. 2",
    employees: [
      {
        id: 1,
        firstName: "Александр",
        lastName: "Ланжерон",
        position: "Прораб",
      },
      {
        id: 2,
        firstName: "Михаил",
        lastName: "Милорадович",
        position: "Инженер-строитель",
      },
      {
        id: 3,
        firstName: "Василий",
        lastName: "Орлов-Денисов",
        position: "Строитель",
      },
      {
        id: 4,
        firstName: "Игнатий",
        lastName: "Пржибышевский",
        position: "Архитектор",
      },
      {
        id: 5,
        firstName: "Николай",
        lastName: "Раевский",
        position: "Монтажник",
      },
      {
        id: 6,
        firstName: "Николай",
        lastName: "Репнин-Волконский",
        position: "Строитель",
      },
      {
        id: 7,
        firstName: "Павел",
        lastName: "Сухтелен",
        position: "Директор",
      },
      {
        id: 8,
        firstName: "Прохор",
        lastName: "Тимохин",
        position: "Инженер",
      },
      {
        id: 9,
        firstName: "Федор",
        lastName: "Уваров",
        position: "Строитель",
      },
      {
        id: 10,
        firstName: "Александр",
        lastName: "Чернышев",
        position: "Архитектор",
      },
    ],
  },
  {
    id: 9,
    name: "МОДУЛЬСТРОЙ",
    address: "г. Новороссийск, с. Гайдук, Новороссийское шоссе, д. 24",
    employees: [
      {
        id: 1,
        firstName: "Иоганн",
        lastName: "фон Шмит",
        position: "Прораб",
      },
      {
        id: 2,
        firstName: "Паисий",
        lastName: "Кайсаров",
        position: "Инженер-строитель",
      },
      {
        id: 3,
        firstName: "Андрей",
        lastName: "Кайсаров",
        position: "Строитель",
      },
      {
        id: 4,
        firstName: "Иван",
        lastName: "Несвицкий",
        position: "Архитектор",
      },
      {
        id: 5,
        firstName: "Карл",
        lastName: "Шуберт",
        position: "Монтажник",
      },
      {
        id: 6,
        firstName: "Александр",
        lastName: "Розен",
        position: "Строитель",
      },
      {
        id: 7,
        firstName: "Огюстен",
        lastName: "Бельяр",
        position: "Директор",
      },
      {
        id: 8,
        firstName: "Жан-Батист",
        lastName: "Бессьер",
        position: "Инженер",
      },
      {
        id: 9,
        firstName: "Луи",
        lastName: "Даву",
        position: "Строитель",
      },
      {
        id: 10,
        firstName: "Луи",
        lastName: "де Коленкур",
        position: "Архитектор",
      },
    ],
  },
  {
    id: 10,
    name: "ДОРТЕХСТРОЙ",
    address: "г. Липецк, ул. Доватора, д. 12-А",
    employees: [
      {
        id: 1,
        firstName: "Жанн",
        lastName: "Ланн",
        position: "Прораб",
      },
      {
        id: 2,
        firstName: "Иоахим",
        lastName: "Мюрат",
        position: "Инженер-строитель",
      },
      {
        id: 3,
        firstName: "Никола",
        lastName: "Удино",
        position: "Строитель",
      },
      {
        id: 4,
        firstName: "Луи",
        lastName: "Бертье",
        position: "Архитектор",
      },
      {
        id: 5,
        firstName: "Жерар",
        lastName: "Дюрок",
        position: "Монтажник",
      },
      {
        id: 6,
        firstName: "Жан",
        lastName: "Рапп",
        position: "Строитель",
      },
      {
        id: 7,
        firstName: "Доминик",
        lastName: "Ларрей",
        position: "Директор",
      },
      {
        id: 8,
        firstName: "Мамелюк",
        lastName: "Раза",
        position: "Инженер",
      },
      {
        id: 9,
        firstName: "Винсент",
        lastName: "Боссе",
        position: "Строитель",
      },
      {
        id: 10,
        firstName: "Алексей",
        lastName: "Аракчеев",
        position: "Архитектор",
      },
    ],
  },
]
